file_types: list[tuple[str, str]] = [
    ("Text File", "*.txt"),
    ("Python File", "*.py"),
    ("HTML File", "*.html"),
    ("CSS File", "*.css"),
    ("SQL File", "*.sql"),
    ("JavaScript File", "*.js"),
    ("Markdown File", "*.md"),
    ("TypeScript File", "*.ts"),
    ("TypeScript with JSX", "*.tsx"),
    ("JavaScript with XML", "*.jsx"),
    ("JSON File", "*.json"),
    ("ENV File", "*.env"),
    ("Config File", "*.cfg"),
    ("TOML File", "*.toml"),
    ("YAML File", "*.yaml"),
    ("GitIgnore File", "*.gitignore"),
]
